### ISSUE TITLE
Use LUA or Go for scripts?

### ISSUE THREAD

**Issue by Nyarum** [Nyarum/noterius#5]
So, currently the official serer files use LUA for script engine.
I can to integrate LUA with custom API to use it for writing script files (Locations, NPCs, items, etc..)

But then we got:
- Slower performance
- Errors in runtime
- Change logic without recompile a server

or the emulator can use Go for scripts and then:
- Best performance like other things in emulator
- Errors on a compile step
- If you change a logic of server you must to recompile it

**Comment by Perseus** [comment]
I'm a supporter of Go. It should be much faster compared to the current architecture.

**Comment by kLabMouse** [comment]
Use LuaJIT binding
It is fast as native and flexible

**Comment by Nyarum** [comment]
@kLabMouse it doesn't look as good idea because
- We'll lost native cross-platform
- Go doesn't has any good binding for LuaJIT

**Comment by kLabMouse** [comment]
I have searched a bit and found some interesting things.
First of. If Script is actually in GO lang. It can be implemented as a plugin and communicate with main via rpc or something similar. Found here: https://stackoverflow.com/questions/18237863/is-it-possible-to-dynamically-load-go-code

Second way is to use some Dynamic language interpreter like
LUA:
https://github.com/Shopify/go-lua
https://github.com/yuin/gopher-lua
https://github.com/icanhas/luajit

JS:
https://github.com/robertkrimen/otto
https://github.com/lazytiger/go-v8

Need to remember, that Flexibility of project itself is very important.

**Comment by Nyarum** [comment]
@kLabMouse of course, different ways is existing in Go. Thank you for research.

First (Dynamic loading)
- Linux-only solution

Second (Script languages)
- This issue exists to discuss about that

If I'll take a library to integrate script language then it'll be - https://github.com/yuin/gopher-lua
It running faster than other libraries by execute time and support modules.

>Need to remember, that Flexibility of project itself is very important.

Flexibility is important, I agree but I think it's not priority feature in choice.

**Comment by Nyarum** [comment]
Another a plus which we'll get with scripting language - it's `hot reload`.
For example, if you add a new NPC to a server then we can get it in a world without any restarts

**Comment by kLabMouse** [comment]
Actually. Dynamic loading/unloading can be made for Windows platform too.
Just need to find a suitable solution.

**Comment by Nyarum** [comment]
So, I made a finally choice, it'll released with https://github.com/hashicorp/go-plugin

First, I'll start write plugins on Go but scripts can be written on any language because this package using gRPC in communication with main process.
Second, it'll faster than VM machine and LUA.
Third, it'll safe all benefits from scripting language.
